name: StaffUI
author: Hirss
version: 1.0
main: Hirss\StaffUI\Main
api: [3.0.0, 4.0.0]
commands:
 smenu:
  description: "Global StaffUI"
 sinfo:
  description: "Staff info"
 tban:
  description: "Open TempBanUI"
  permission: use.tban
 tcheck:
  description: "Check ban list"
  permission: use.tcheck
  
